export const PSYCHE_FACTS = [
  'Psyche was discovered in the mid 1800s by astronomer Annibale de Gasparis. It was the 16th asteroid ever found.',
  'Psyche resides in the Asteroid Belt between Mars and Jupiter.',
  'If Psyche were a perfect sphere, it would be about the length of Massachusetts (leaving out Cape Cod).',
  'Psyche may be the nickel-iron metal core of a protoplanet, though we will need a closer look to be sure.',
  'The mission to Psyche is an orbiter mission, led by Principal Investigator Dr. Lindy Elkins-Tanton of ASU.',
  'The goal of the Psyche mission is to send a robotic spacecraft to the asteroid for observations from a series of orbits.',
  'Overall Psyche mission timeline: Launch 2022, Arrive 2026, Orbit for 21 months.',
  "The Psyche mission's robotic spacecraft is about the size of a single tennis court.",
  "The Psyche mission's spacecraft contains the following: Multispectral Imager (ASU), Gamma Ray and Neutron Spectrometer (APL), Magnetometer (MIT/UCLA), X-band radio telecommunications (MIT/JPL), Deep Space Optical Communications (JPL).",
  "The Psyche mission's spacecraft will reach the asteroid using low-thrust solar electric propulsion.",
  'What makes the asteroid Psyche unique is that it appears to be the exposed nickel-iron core of an early planet, one of the building blocks of our solar system.',
  'The Psyche mission is led by Arizona State University.',
  "NASA's Jet Propulsion Laboratory is responsible for the Psyche mission's management, operations, and navigation.",
  "The Psyche mission spacecraft's solar-electric propulsion chassis will be built by Maxar with a payload that includes an imager, magnetometer, and a gamma-ray spectrometer.",
  'The Psyche mission will test a sophisticated new laser communication technology that encodes data in photons (rather than radio waves) to communicate between a probe in deep space and Earth.',
  'The Psyche spacecraft will launch in 2022 from Kennedy Space Center in Florida.',
  'The Psyche spacecraft will use gravity assist with a Mars flyby in 2023.',
  "The Psyche spacecraft will arrive in the asteroid's orbit in 2026.",
  'The Psyche spacecraft will orbit the Psyche asteroid from 2026-2027.',
  'Psyche is both the name of an asteroid orbiting the Sun between Mars and Jupiter — and the name of an ASU mission to visit that asteroid.',
  "The Psyche mission was chosen by NASA on January 4, 2017 as one of two missions for the agency's Discovery Program, a series of low-cost missions to solar system targets.",
  'After arrival, the Psyche mission plan calls for 21 months spent on the asteroid, mapping it and studying its properties.',
  'NASA Psyche Mission Principal Investigator, Dr. Lindy Elkins-Tanton, started the hashtag #PI_Daily to share her own daily Psyche mission updates.',
  'Psyche is the first mission to explore a world made not of rock or ice, but metal.',
  'Psyche takes about five Earth years to complete one orbit of the Sun, but only a bit over four hours to rotate once on its axis (a Psyche "day").',
  "The Psyche asteroid was named after the nymph Psyche, who married Cupid but was put to death by Venus. At Cupid's request, however, Jupiter made Psyche immortal.",
  "Unlike most other asteroids that are rocky or icy bodies, scientists think the M-type (metallic) asteroid 16 Psyche is composed mostly of metallic iron and nickel similar to Earth's core.",
  'Scientists wonder whether Psyche could be an exposed core of an early planet, maybe as large as Mars, that lost its rocky outer layers due to a number of violent collisions billions of years ago.',
  'Astronomers on Earth have studied 16 Psyche in visible and infrared wavelengths, as well as radar, which suggest Psyche is shaped somewhat like a potato.',
  'The Psyche mission will be the first mission to investigate a world of metal rather than of rock and ice.',
  "Because scientists cannot see or measure Earth's core directly, Psyche offers a unique window into the violent history of collisions and accretion that created terrestrial planets.",
  "The Psyche mission's magnetometer is designed to detect and measure the remnant magnetic field of the asteroid.",
  "The Psyche mission's multispectral imager will provide high-resolution images using filters to discriminate between Psyche's metallic and silicate constituents.",
  "The Psyche mission's gamma ray and neutron spectrometer will detect, measure and map Psyche's elemental composition.",
  'The Psyche mission also will test a sophisticated new laser communications technology, called Deep Space Optical Communications.',
];
